profiles:
  development:
    base_url: http://localhost:4242/
    disqus: jidpl
  production:
    base_url: http://www.jid.pl
    disqus: jidpl
    deploy:
      host: github_pages
  openshift:
    baseurl: http://website-goldmann.rhcloud.com
    deploy:
      type: openshift
      username: b98815a6002846f3adcc2088eee99ca5
      host: website-goldmann.rhcloud.com
      appname: website
      path: php

google_analytics: UA-351971-2
